### ISSUE TITLE
Add dynamic provisioning of creating or joining ETCD cluster

### ISSUE THREAD

**Issue by jwitko** [blinklabs-io/ansible-cardano#2]
* https://etcd.io/docs/latest/dev-internal/discovery_protocol/#public-discovery-service
* Enable or disable this feature via config passed into ansible
* Take UUID for ETCD cluster as input into ansible
* Use ETCD public discovery service to either establish or join an ETCD cluster

**Comment by wolf31o2** [comment]
Closing this. It was part of a design we're not going to continue here.
